name: jiralert
app: jiralert

deployment:
  containerName: jiralert
  image: martinlillemetscb/jiralert-linux-amd64:latest
  args:
    - "--config=/jiralert-config/jiralert.yml"
    - "--log.level=debug"
    - "--listen-address=:9097"
    - "--hash-jira-label"
  volume:
    name: jiralert-config
    readOnly: true
service:
  app: jiralert-service
  type: ClusterIP
  port: 9097
  targetPort: 9097
  nodeport: 30097
secret:
  name: jiralert-config
config:
  # Global defaults, applied to all receivers where not explicitly overridden.
  template: jiralert.tmpl

  # Global access values
  #api_url: https://myjira.atlassian.net
  #user: username@example.com
  #password: 'password'

  # The type of JIRA issue to create. Required.
  issue_type: "Bug"
  # Issue priority. Optional.
  priority: "Highest"
  # Go template invocation for generating the summary. Required.
  summary: '{{ template "jira.summary" . }}'
  # Go template invocation for generating the description. Optional.
  description: '{{ template "jira.description" . }}'
  # State to transition into when reopening a closed issue. Required.
  reopen_state: "Reopened"
  # Do not reopen issues with this resolution. Optional.
  wont_fix_resolution: "Won't Fix"
  # Amount of time after being closed that an issue should be reopened, after which, a new issue is created.
  # Optional (default: always reopen)
  reopen_duration: 0h

  # Receiver definitions. At least one must be defined.
  # Receiver names must match the Alertmanager receiver names. Required.
#  receivers:
#    - name: jira-al
#      project: AL
