apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
  ports:
  - port: 9097
    targetPort: 9097
    {{ if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodeport }}
    {{ end }}
